trigger:
  branches:
    include:
      - main

parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: apply
  values:
    - apply
    - destroy

variables:
  TF_VERSION: "1.6.6"
  AWS_REGION: "us-east-1"

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  displayName: Terraform Infra Stage
  jobs:
  - job: TerraformJob
    displayName: Terraform Apply or Destroy
    steps:

    # Install Terraform
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)

    # Verify AWS Credentials
    - task: AWSCLI@1
      displayName: AWS Identity Check
      inputs:
        awsCredentials: "aws-service-connection"
        regionName: $(AWS_REGION)
        awsCommand: "sts"
        awsSubCommand: "get-caller-identity"

    # Terraform Init
    - script: |
        terraform init -input=false
      displayName: Terraform Init
      workingDirectory: infra

    # Terraform Validate
    - script: |
        terraform validate
      displayName: Terraform Validate
      workingDirectory: infra

    # Terraform Plan
    - script: |
        terraform plan -out=tfplan
      displayName: Terraform Plan
      workingDirectory: infra

    # Apply or Destroy
    - script: |
        if [ "${{ parameters.action }}" = "apply" ]; then
          terraform apply -auto-approve tfplan
        else
          terraform destroy -auto-approve
        fi
      displayName: Terraform Apply or Destroy
      workingDirectory: infra
