trigger:
  branches:
    include:
      - main

parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: apply
  values:
    - apply
    - destroy

variables:
  TF_VERSION: "1.6.6"
  AWS_REGION: "us-east-1"
  TF_STATE_BUCKET: "your-terraform-state-bucket"
  TF_STATE_KEY: "eks/terraform.tfstate"

pool:
  vmImage: ubuntu-latest   # Microsoft-hosted agent

stages:
- stage: Terraform
  displayName: Terraform Infrastructure
  jobs:
  - job: TerraformJob
    displayName: Terraform Apply or Destroy
    steps:

    # -------------------------
    # Install Terraform
    # -------------------------
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)

    # -------------------------
    # Terraform Init (S3 backend)
    # -------------------------
    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: aws
        command: init
        backendServiceAWS: aws_mohamedSaleh
        backendAWSRegion: $(AWS_REGION)
        backendAWSBucketName: nti-terraform-states
        backendAWSKey: eks/terraform.tfstate
    # -------------------------
    # Terraform Validate
    # -------------------------
    - task: TerraformTaskV4@4
      displayName: Terraform Validate
      inputs:
        provider: aws
        command: validate

    # -------------------------
    # Terraform Plan
    # -------------------------
    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: aws
        command: plan
        environmentServiceNameAWS: aws_mohamedSaleh
        commandOptions: "-out=tfplan"

    # -------------------------
    # Terraform Apply OR Destroy
    # -------------------------
    - ${{ if eq(parameters.action, 'apply') }}:
      - task: TerraformTaskV4@4
        displayName: Terraform Apply
        inputs:
          provider: aws
          command: apply
          environmentServiceNameAWS: aws_mohamedSaleh
          commandOptions: "-auto-approve tfplan"

    - ${{ if eq(parameters.action, 'destroy') }}:
      - task: TerraformTaskV4@4
        displayName: Terraform Destroy
        inputs:
          provider: aws
          command: destroy
          environmentServiceNameAWS: aws_mohamedSaleh
          commandOptions: "-auto-approve"
