trigger:
  branches:
    include:
      - main

parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: apply
  values:
    - apply
    - destroy

variables:
  TF_VERSION: "1.6.6"
  AWS_REGION: "us-east-1"
  TF_STATE_BUCKET: "nti-terraform-states"
  TF_STATE_KEY: "eks/terraform.tfstate"

# -----------------------------
# Use Microsoft-hosted agent
# -----------------------------
pool:
  vmImage: ubuntu-latest   # Azure DevOps chooses the agent

stages:
- stage: Terraform
  displayName: Terraform Infrastructure
  jobs:
  - job: TerraformJob
    displayName: Terraform Apply or Destroy
    steps:

    # -------------------------
    # Install Terraform
    # -------------------------
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)

    # -------------------------
    # Terraform Init (S3 backend)
    # -------------------------
    - script: |
        echo "Initializing Terraform with S3 backend..."
        export AWS_ACCESS_KEY_ID=$(aws_access_key_id_from_service_connection)
        export AWS_SECRET_ACCESS_KEY=$(aws_secret_access_key_from_service_connection)
        terraform init \
          -backend-config="bucket=$(TF_STATE_BUCKET)" \
          -backend-config="key=$(TF_STATE_KEY)" \
          -backend-config="region=$(AWS_REGION)"
      displayName: Terraform Init

    # -------------------------
    # Terraform Validate
    # -------------------------
    - script: |
        echo "Validating Terraform configuration..."
        terraform validate
      displayName: Terraform Validate

    # -------------------------
    # Terraform Plan
    # -------------------------
    - script: |
        echo "Creating Terraform plan..."
        terraform plan -out=tfplan
      displayName: Terraform Plan

    # -------------------------
    # Terraform Apply OR Destroy
    # -------------------------
    - ${{ if eq(parameters.action, 'apply') }}:
      - script: |
          echo "Applying Terraform plan..."
          terraform apply -auto-approve tfplan
        displayName: Terraform Apply

    - ${{ if eq(parameters.action, 'destroy') }}:
      - script: |
          echo "Destroying Terraform infrastructure..."
          terraform destroy -auto-approve
        displayName: Terraform Destroy
