trigger:
  branches:
    include:
      - main

parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: apply
  values:
    - apply
    - destroy

variables:
  TF_VERSION: "1.6.6"
  AWS_REGION: "us-east-1"
  TF_STATE_BUCKET: "nti-terraform-states"
  TF_STATE_KEY: "eks/terraform.tfstate"

# -----------------------------
# Use EC2 self-hosted agent
# -----------------------------
pool:
  name: Self hosted pools      # اسم الـ Agent Pool في Azure DevOps
  demands:
    - agent.name -equals ip-172-31-33-153   # اسم الـ agent على الـ EC2

stages:
- stage: Terraform
  displayName: Terraform Infrastructure
  jobs:
  - job: TerraformJob
    displayName: Terraform Apply or Destroy
    steps:

    # -------------------------
    # Install Terraform
    # -------------------------
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)

    # -------------------------
    # Terraform Init (S3 backend)
    # -------------------------
    - script: |
        terraform init \
          -backend-config="bucket=$(TF_STATE_BUCKET)" \
          -backend-config="key=$(TF_STATE_KEY)" \
          -backend-config="region=$(AWS_REGION)"
      displayName: Terraform Init

    # -------------------------
    # Terraform Validate
    # -------------------------
    - script: terraform validate
      displayName: Terraform Validate

    # -------------------------
    # Terraform Plan
    # -------------------------
    - script: terraform plan -out=tfplan
      displayName: Terraform Plan

    # -------------------------
    # Terraform Apply OR Destroy
    # -------------------------
    - ${{ if eq(parameters.action, 'apply') }}:
      - script: terraform apply -auto-approve tfplan
        displayName: Terraform Apply

    - ${{ if eq(parameters.action, 'destroy') }}:
      - script: terraform destroy -auto-approve
        displayName: Terraform Destroy
