trigger:
  branches:
    include:
      - main

parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: apply
  values:
    - apply
    - destroy

variables:
  TF_VERSION: "1.6.6"
  AWS_REGION: "us-east-1"
  TF_STATE_BUCKET: "nti-terraform-states"
  TF_STATE_KEY: "eks/terraform.tfstate"
  AWS_CONNECTION: "aws_mohamedSaleh"   # اسم AWS Service Connection

stages:
- stage: Terraform
  displayName: Terraform Infrastructure
  jobs:
  - job: TerraformJob
    displayName: Terraform Apply or Destroy
    steps:

    # -------------------------
    # Configure AWS Credentials using Service Connection
    # -------------------------
    - task: AwsCli@1
      displayName: Configure AWS Credentials
      inputs:
        awsCredentials: $(AWS_CONNECTION)
        regionName: $(AWS_REGION)
        awsCommand: sts
        awsSubCommand: get-caller-identity
      
      
      # -------------------------
    # Install Terraform
    # -------------------------
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)

    # -------------------------
    # Terraform Init
    # -------------------------
    - script: |
        cd Cluster
        terraform init \
          -backend-config="bucket=$(TF_STATE_BUCKET)" \
          -backend-config="key=$(TF_STATE_KEY)" \
          -backend-config="region=$(AWS_REGION)"
      displayName: Terraform Init

    # -------------------------
    # Terraform Validate
    # -------------------------
    - script: |
        cd Cluster
        terraform validate
      displayName: Terraform Validate

    # -------------------------
    # Terraform Plan
    # -------------------------
    - script: |
        cd Cluster
        terraform plan -out=tfplan
      displayName: Terraform Plan

    # -------------------------
    # Terraform Apply or Destroy
    # -------------------------
    - ${{ if eq(parameters.action, 'apply') }}:
      - script: |
          cd Cluster
          terraform apply -auto-approve tfplan
        displayName: Terraform Apply

    - ${{ if eq(parameters.action, 'destroy') }}:
      - script: |
          cd Cluster
          terraform destroy -auto-approve
        displayName: Terraform Destroy
