trigger:
  branches:
    include:
      - main

parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: apply
  values:
    - apply
    - destroy

variables:
  TF_VERSION: "1.6.6"
  AWS_REGION: "us-east-1"
  TF_STATE_BUCKET: "nti-terraform-states"
  TF_STATE_KEY: "eks/terraform.tfstate"

pool:
  name: Self hosted pools
  demands:
    - agent.name -equals mo-saleh

stages:
- stage: Terraform
  displayName: Terraform Infrastructure
  jobs:
  - job: TerraformJob
    displayName: Terraform Apply or Destroy
    steps:

    # -------------------------
    # Install Terraform
    # -------------------------
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)

    # -------------------------
    # Terraform Init
    # -------------------------
    - script: |
        cd Cluster
        terraform init \
          -backend-config="bucket=$(TF_STATE_BUCKET)" \
          -backend-config="key=$(TF_STATE_KEY)" \
          -backend-config="region=$(AWS_REGION)"
      displayName: Terraform Init

    # -------------------------
    # Terraform Validate
    # -------------------------
    - script: |
        cd Cluster
        terraform validate
      displayName: Terraform Validate

    # -------------------------
    # Terraform Plan
    # -------------------------
    - script: |
        cd Cluster
        terraform plan -out=tfplan
      displayName: Terraform Plan

    # -------------------------
    # Terraform Apply or Destroy
    # -------------------------
    - ${{ if eq(parameters.action, 'apply') }}:
      - script: |
          cd Cluster
          terraform apply -auto-approve tfplan
        displayName: Terraform Apply

      # -------------------------
      # Update kubeconfig & Check Nodes
      # -------------------------
      - script: |
          cd Cluster
          export KUBECONFIG=$(pwd)/kubeconfig
          aws eks update-kubeconfig --region $(AWS_REGION) --name $(terraform output -raw cluster_name)
          echo "Cluster Name: $(terraform output -raw cluster_name)"
          echo "VPC ID: $(terraform output -raw vpc_id)"
          echo "Public Subnets: $(terraform output -raw public_subnets)"
          echo "Private Subnets: $(terraform output -raw private_subnets)"
          echo "Node Groups:"
          aws eks list-nodegroups --cluster-name $(terraform output -raw cluster_name) --region $(AWS_REGION)
          kubectl get nodes -o wide
        displayName: Update kubeconfig & Check Nodes

    - ${{ if eq(parameters.action, 'destroy') }}:
      - script: |
          cd Cluster
          terraform destroy -auto-approve
        displayName: Terraform Destroy
